import { useState, useEffect } from "react";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Loader2, TrendingUp, BarChart3, Download } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import { supabase } from "@/integrations/supabase/client";
import jsPDF from "jspdf";

interface AnalysisTabProps {
  projectKey: string;
}

interface Plan {
  name: string;
  features: { [key: string]: string };
  suggestedPrice: number;
  willingnessToPay: number;
  currency?: string;
  rationale?: string;
}

interface AnalysisResults {
  importances: { [key: string]: number };
  utilities: { [key: string]: number };
  totalResponses: number;
  analysisTabName: string;
  plans: Plan[];
  currency?: string;
  priceMismatchWarning?: string;
}

export const AnalysisTab = ({ projectKey }: AnalysisTabProps) => {
  const [loading, setLoading] = useState(false);
  const [results, setResults] = useState<AnalysisResults | null>(null);
  const [numPlans, setNumPlans] = useState<number>(3);
  const [pricingStrategy, setPricingStrategy] = useState<"submitted" | "suggested">("suggested");
  const [goal, setGoal] = useState<"revenue" | "purchases">("revenue");
  const [noResponses, setNoResponses] = useState(false);
  const [priceWarning, setPriceWarning] = useState<string>("");
  const [successMessage, setSuccessMessage] = useState<string>("");
  const { toast } = useToast();

  // Fetch attributes to set default number of plans based on pricing levels
  useEffect(() => {
    const fetchPricingLevels = async () => {
      try {
        const { data, error } = await supabase.functions.invoke("get-attributes", {
          body: { projectKey },
        });

        if (!error && data?.attributes) {
          const pricingAttr = data.attributes.find((attr: any) => attr.isPriceAttribute);
          if (pricingAttr && pricingAttr.levels && pricingAttr.levels.length > 0) {
            setNumPlans(pricingAttr.levels.length);
          }
        }
      } catch (err) {
        console.error("Error fetching pricing levels:", err);
      }
    };

    fetchPricingLevels();
  }, [projectKey]);

  const downloadPDF = () => {
    if (!results) return;

    const doc = new jsPDF();
    const currency = results.currency || "USD";
    const currencySymbol = currency === "USD" ? "$" : currency === "EUR" ? "€" : currency === "GBP" ? "£" : currency;
    let yPos = 15;

    // Header with link
    doc.setFontSize(9);
    doc.setFont(undefined, "normal");
    doc.setTextColor(100, 100, 100);
    const headerText = "Generated by Plan Builder by Experiment Nation";
    doc.textWithLink(headerText, 105, yPos, {
      align: "center",
      url: "https://experimentnation.com/consulting",
    });
    yPos += 10;

    // Title
    doc.setFontSize(20);
    doc.setFont(undefined, "bold");
    doc.setTextColor(0, 0, 0);
    doc.text("Plan Builder Analysis Report", 105, yPos, { align: "center" });
    yPos += 12;

    // Metadata box
    doc.setFontSize(10);
    doc.setFont(undefined, "normal");
    doc.setFillColor(245, 245, 250);
    doc.rect(20, yPos, 170, 20, "F");
    yPos += 6;
    doc.text(`Total Responses: ${results.totalResponses}`, 25, yPos);
    yPos += 5;
    doc.text(`Analysis Date: ${new Date().toLocaleDateString()}`, 25, yPos);
    yPos += 5;
    doc.text(`Currency: ${currency}`, 25, yPos);
    yPos += 5;
    doc.text(`Goal: ${goal === "revenue" ? "Maximize Revenue" : "Maximize Purchases"}`, 25, yPos);
    yPos += 12;

    // Attribute Importances
    doc.setFontSize(16);
    doc.setFont(undefined, "bold");
    doc.text("Attribute Importances", 20, yPos);
    yPos += 8;

    doc.setFontSize(9);
    doc.setTextColor(100, 100, 100);
    doc.text("Shows which attributes have the most influence on choices", 20, yPos);
    yPos += 8;

    doc.setFont(undefined, "normal");
    doc.setTextColor(0, 0, 0);
    Object.entries(results.importances)
      .sort(([, a], [, b]) => b - a)
      .forEach(([attr, importance]) => {
        doc.setFontSize(10);
        doc.text(`${attr}`, 25, yPos);
        doc.text(`${importance.toFixed(1)}%`, 180, yPos, { align: "right" });

        // Draw progress bar
        const barWidth = 120;
        const barHeight = 4;
        const filledWidth = (importance / 100) * barWidth;
        doc.setDrawColor(200, 200, 200);
        doc.setFillColor(200, 200, 200);
        doc.rect(25, yPos + 2, barWidth, barHeight, "F");
        doc.setFillColor(139, 92, 246); // Purple
        doc.rect(25, yPos + 2, filledWidth, barHeight, "F");

        yPos += 10;
      });
    yPos += 8;

    // Part-Worth Utilities
    if (yPos > 230) {
      doc.addPage();
      yPos = 20;
    }

    doc.setFontSize(16);
    doc.setFont(undefined, "bold");
    doc.text("Part-Worth Utilities", 20, yPos);
    yPos += 8;

    doc.setFontSize(9);
    doc.setFont(undefined, "normal");
    doc.setTextColor(100, 100, 100);
    doc.text("Higher values indicate more preferred attribute levels", 20, yPos);
    yPos += 10;

    doc.setTextColor(0, 0, 0);
    doc.setFontSize(9);
    doc.setFont(undefined, "bold");
    doc.text("Attribute:Level", 25, yPos);
    doc.text("Utility", 180, yPos, { align: "right" });
    yPos += 1;
    doc.setLineWidth(0.5);
    doc.line(25, yPos, 185, yPos);
    yPos += 4;

    doc.setFont(undefined, "normal");
    Object.entries(results.utilities).forEach(([key, utility]) => {
      if (yPos > 270) {
        doc.addPage();
        yPos = 20;
      }
      doc.setFontSize(9);
      doc.text(key, 25, yPos);
      doc.text(utility.toFixed(3), 180, yPos, { align: "right" });
      yPos += 5;
    });
    yPos += 10;

    // Recommended Plans
    if (results.plans && results.plans.length > 0) {
      doc.addPage();
      yPos = 20;

      doc.setFontSize(16);
      doc.setFont(undefined, "bold");
      doc.text("Recommended Plans", 20, yPos);
      yPos += 8;

      doc.setFontSize(9);
      doc.setFont(undefined, "normal");
      doc.setTextColor(100, 100, 100);
      const goalText =
        goal === "revenue"
          ? "Plans ordered from lowest to highest revenue potential"
          : "Plans ordered from lowest to highest expected adoption";
      doc.text(goalText, 20, yPos);
      yPos += 8;

      // Add price mismatch warning if present
      if (results.priceMismatchWarning) {
        doc.setFontSize(8);
        doc.setTextColor(139, 92, 246);
        doc.setFillColor(245, 240, 255);
        const warningLines = doc.splitTextToSize(results.priceMismatchWarning, 170);
        const warningHeight = warningLines.length * 4 + 6;
        doc.rect(20, yPos, 170, warningHeight, "F");
        doc.text(warningLines, 25, yPos + 4);
        yPos += warningHeight + 4;
      }

      yPos += 4;

      doc.setTextColor(0, 0, 0);

      results.plans.forEach((plan, idx) => {
        if (yPos > 220) {
          doc.addPage();
          yPos = 20;
        }

        // Plan box
        doc.setDrawColor(139, 92, 246);
        doc.setLineWidth(0.5);
        doc.rect(20, yPos - 5, 170, 8, "S");

        doc.setFontSize(14);
        doc.setFont(undefined, "bold");
        doc.text(plan.name, 25, yPos);
        yPos += 10;

        // Pricing
        doc.setFontSize(20);
        doc.setTextColor(139, 92, 246);
        doc.text(`${currencySymbol}${plan.suggestedPrice}`, 25, yPos);
        doc.setFontSize(10);
        doc.setTextColor(100, 100, 100);
        doc.text("/period", 25 + doc.getTextWidth(`${currencySymbol}${plan.suggestedPrice}`) * (20 / 10), yPos);
        yPos += 8;

        doc.setFontSize(9);
        doc.text(`Willingness to Pay: ${currencySymbol}${plan.willingnessToPay.toFixed(2)}`, 25, yPos);
        yPos += 10;

        // Features
        doc.setTextColor(0, 0, 0);
        doc.setFontSize(10);
        doc.setFont(undefined, "bold");
        doc.text("Features:", 25, yPos);
        yPos += 6;

        doc.setFont(undefined, "normal");
        doc.setFontSize(9);
        Object.entries(plan.features).forEach(([attr, level]) => {
          doc.text(`• ${attr}: ${level}`, 30, yPos);
          yPos += 5;
        });
        yPos += 8;
      });
    }

    doc.save("plan-builder-analysis.pdf");

    toast({
      title: "PDF Downloaded",
      description: "Analysis report has been downloaded successfully",
    });
  };

  const runAnalysis = async () => {
    setLoading(true);
    setNoResponses(false);
    setPriceWarning("");
    setSuccessMessage("");
    try {
      const { data, error } = await supabase.functions.invoke("run-analysis", {
        body: {
          projectKey,
          numPlans,
          pricingStrategy,
          goal,
        },
      });

      if (error) {
        throw new Error(error.message || "Failed to run analysis");
      }

      if (!data || !data.results) {
        throw new Error("No analysis results returned");
      }

      setResults(data.results);

      // Set warning if there's a price mismatch
      if (data.results.priceMismatchWarning) {
        setPriceWarning(data.results.priceMismatchWarning);
      }

      // Set success message
      setSuccessMessage(`Results saved to ${data.results.analysisTabName} tab in your Google Sheet`);
    } catch (err: any) {
      // Check if error is about no responses
      if (err.message && err.message.toLowerCase().includes("no responses found")) {
        setNoResponses(true);
      } else {
        toast({
          title: "Error",
          description: err.message,
          variant: "destructive",
        });
      }
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="space-y-6">
      <Card className="shadow-card p-6">
        <div className="mb-6">
          <h2 className="text-2xl font-semibold mb-2">Conjoint Analysis</h2>
          <p className="text-sm text-muted-foreground">
            Run statistical analysis on your survey responses to calculate attribute importances and generate pricing
            plans
          </p>
        </div>

        <div className="space-y-6 mb-6">
          <div className="max-w-xs">
            <Label htmlFor="numPlans">Number of Plans to Generate</Label>
            <Input
              id="numPlans"
              type="number"
              min="1"
              max="10"
              value={numPlans}
              onChange={(e) => setNumPlans(parseInt(e.target.value) || 3)}
              className="mt-2"
            />
            <p className="mt-1 text-xs text-muted-foreground">Generate good, better, best pricing plans (1-10 plans)</p>
          </div>

          <div>
            <Label className="text-base mb-3 block">Goal</Label>
            <div className="space-y-3">
              <div className="flex items-start space-x-3">
                <input
                  type="radio"
                  id="revenue"
                  name="goal"
                  value="revenue"
                  checked={goal === "revenue"}
                  onChange={(e) => setGoal(e.target.value as "revenue" | "purchases")}
                  className="mt-0.5 h-4 w-4 text-primary focus:ring-primary"
                />
                <div className="flex-1">
                  <Label htmlFor="revenue" className="font-medium cursor-pointer">
                    Maximize Revenue
                  </Label>
                  <p className="text-xs text-muted-foreground mt-1">
                    Optimize plans for higher prices and total revenue
                  </p>
                </div>
              </div>
              <div className="flex items-start space-x-3">
                <input
                  type="radio"
                  id="purchases"
                  name="goal"
                  value="purchases"
                  checked={goal === "purchases"}
                  onChange={(e) => setGoal(e.target.value as "revenue" | "purchases")}
                  className="mt-0.5 h-4 w-4 text-primary focus:ring-primary"
                />
                <div className="flex-1">
                  <Label htmlFor="purchases" className="font-medium cursor-pointer">
                    Maximize Purchases
                  </Label>
                  <p className="text-xs text-muted-foreground mt-1">
                    Optimize plans for affordability and customer acquisition
                  </p>
                </div>
              </div>
            </div>
          </div>

          <div>
            <Label className="text-base mb-3 block">Pricing Strategy</Label>
            <div className="space-y-3">
              <div className="flex items-start space-x-3">
                <input
                  type="radio"
                  id="suggested"
                  name="pricingStrategy"
                  value="suggested"
                  checked={pricingStrategy === "suggested"}
                  onChange={(e) => setPricingStrategy(e.target.value as "submitted" | "suggested")}
                  className="mt-0.5 h-4 w-4 text-primary focus:ring-primary"
                />
                <div className="flex-1">
                  <Label htmlFor="suggested" className="font-medium cursor-pointer">
                    Let Plan Builder suggest pricing
                  </Label>
                  <p className="text-xs text-muted-foreground mt-1">
                    Uses willingness to pay and utility values to recommend optimal pricing
                  </p>
                </div>
              </div>
              <div className="flex items-start space-x-3">
                <input
                  type="radio"
                  id="submitted"
                  name="pricingStrategy"
                  value="submitted"
                  checked={pricingStrategy === "submitted"}
                  onChange={(e) => setPricingStrategy(e.target.value as "submitted" | "suggested")}
                  className="mt-0.5 h-4 w-4 text-primary focus:ring-primary"
                />
                <div className="flex-1">
                  <Label htmlFor="submitted" className="font-medium cursor-pointer">
                    Use the submitted pricing levels
                  </Label>
                  <p className="text-xs text-muted-foreground mt-1">
                    Uses exact price levels from your survey responses
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>

        <Button onClick={runAnalysis} disabled={loading} className="gradient-primary" size="lg">
          {loading ? (
            <>
              <Loader2 className="mr-2 h-5 w-5 animate-spin" />
              Running Analysis...
            </>
          ) : (
            <>
              <TrendingUp className="mr-2 h-5 w-5" />
              Analyze Results
            </>
          )}
        </Button>

        {successMessage && (
          <div className="mt-4 p-4 bg-primary/10 border border-primary/30 rounded-lg">
            <p className="text-sm text-primary font-medium">✓ Analysis Complete! {successMessage}</p>
          </div>
        )}

        {priceWarning && (
          <div className="mt-4 p-4 bg-destructive/10 border border-destructive/30 rounded-lg">
            <p className="text-sm text-destructive font-medium whitespace-pre-line">{priceWarning}</p>
          </div>
        )}

        {noResponses && (
          <div className="mt-8 rounded-lg border-2 border-dashed border-border p-8 text-center">
            <BarChart3 className="mx-auto h-16 w-16 text-muted-foreground mb-4" />
            <h3 className="text-xl font-semibold mb-2">No Responses Yet</h3>
            <p className="text-muted-foreground mb-4">You need to collect survey responses before running analysis.</p>
            <p className="text-sm text-muted-foreground">
              Go to the <span className="font-medium">Generate Links</span> tab to create and share your survey link.
            </p>
          </div>
        )}

        {!results && !loading && !noResponses && (
          <div className="mt-8 rounded-lg bg-muted/50 p-6">
            <h3 className="mb-3 text-lg font-semibold">What This Does</h3>
            <ul className="space-y-2 text-sm text-muted-foreground">
              <li>• Reads all survey responses from your Google Sheet</li>
              <li>• Calculates attribute importances (which features matter most)</li>
              <li>• Estimates part-worth utilities for each attribute level</li>
              <li>• Saves detailed results to a new Analysis tab in your sheet</li>
            </ul>
          </div>
        )}
      </Card>

      {results && (
        <Card className="shadow-card p-6">
          <div className="mb-4 flex items-center justify-between">
            <div className="flex items-center gap-2">
              <BarChart3 className="h-5 w-5 text-primary" />
              <h3 className="text-xl font-semibold">Analysis Results</h3>
            </div>
            <Button onClick={downloadPDF} variant="outline" size="sm">
              <Download className="mr-2 h-4 w-4" />
              Download PDF
            </Button>
          </div>

          <div className="space-y-6">
            <div>
              <div className="mb-4 rounded-lg bg-accent/10 p-4">
                <p className="text-sm text-muted-foreground">
                  Based on <span className="font-semibold text-foreground">{results.totalResponses}</span> responses
                </p>
              </div>

              <h4 className="mb-3 text-lg font-semibold">Attribute Importances</h4>
              <p className="mb-4 text-xs text-muted-foreground">
                Shows which attributes have the most influence on choices
              </p>
              <div className="space-y-3">
                {Object.entries(results.importances)
                  .sort(([, a], [, b]) => b - a)
                  .map(([attr, importance]) => (
                    <div key={attr} className="space-y-1">
                      <div className="flex items-center justify-between text-sm">
                        <span className="font-medium">{attr}</span>
                        <span className="text-muted-foreground">{importance.toFixed(1)}%</span>
                      </div>
                      <div className="h-2 w-full rounded-full bg-muted overflow-hidden">
                        <div className="h-full bg-primary transition-all" style={{ width: `${importance}%` }} />
                      </div>
                    </div>
                  ))}
              </div>
            </div>

            <div>
              <h4 className="mb-3 text-lg font-semibold">Part-Worth Utilities</h4>
              <p className="mb-4 text-xs text-muted-foreground">
                Higher values indicate more preferred attribute levels
              </p>
              <div className="rounded-lg border">
                <div className="grid grid-cols-2 gap-px bg-border">
                  <div className="bg-muted px-4 py-2 font-semibold text-sm">Attribute:Level</div>
                  <div className="bg-muted px-4 py-2 font-semibold text-sm text-right">Utility</div>
                  {Object.entries(results.utilities).map(([key, utility]) => (
                    <>
                      <div className="bg-background px-4 py-2 text-sm">{key}</div>
                      <div className="bg-background px-4 py-2 text-sm text-right font-mono">{utility.toFixed(3)}</div>
                    </>
                  ))}
                </div>
              </div>
            </div>

            {results.plans && results.plans.length > 0 && (
              <div>
                <h4 className="mb-3 text-lg font-semibold">Recommended Plans</h4>
                <p className="mb-4 text-xs text-muted-foreground">
                  {goal === "revenue"
                    ? "Plans ordered from lowest to highest revenue potential"
                    : "Plans ordered from lowest to highest expected adoption"}
                </p>
                {results.priceMismatchWarning && (
                  <div className="mb-4 p-4 bg-accent/10 border border-accent/20 rounded-lg">
                    <p className="text-sm text-foreground whitespace-pre-line">{results.priceMismatchWarning}</p>
                  </div>
                )}
                <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
                  {results.plans.map((plan, idx) => {
                    const currency = results.currency || plan.currency || "USD";
                    const currencySymbol =
                      currency === "USD" ? "$" : currency === "EUR" ? "€" : currency === "GBP" ? "£" : currency;

                    return (
                      <Card
                        key={idx}
                        className="p-6 border-2 border-primary/20 hover:border-primary/40 transition-colors"
                      >
                        <h5 className="text-lg font-bold mb-2">{plan.name}</h5>
                        <div className="mb-4">
                          <div className="text-3xl font-bold text-primary">
                            {currencySymbol}
                            {plan.suggestedPrice}
                          </div>
                          <div className="text-sm text-muted-foreground">/period</div>
                          <div className="mt-1 text-xs text-muted-foreground">
                            WTP: {currencySymbol}
                            {plan.willingnessToPay.toFixed(2)}
                          </div>
                        </div>
                        {plan.rationale && (
                          <p className="text-sm text-muted-foreground mb-4 italic">{plan.rationale}</p>
                        )}
                        <div className="space-y-2">
                          <p className="text-xs font-semibold text-muted-foreground uppercase">Features:</p>
                          {Object.entries(plan.features).map(([attr, level]) => (
                            <div key={attr} className="text-sm">
                              <span className="font-medium">{attr}:</span> {level}
                            </div>
                          ))}
                        </div>
                      </Card>
                    );
                  })}
                </div>
              </div>
            )}

            <div className="rounded-lg bg-accent/10 p-4">
              <p className="text-sm">
                <strong>Note:</strong> Full results have been saved to the{" "}
                <span className="font-mono text-xs">{results.analysisTabName}</span> tab in your Google Sheet
              </p>
            </div>

            <div className="flex justify-center pt-4">
              <Button onClick={downloadPDF} variant="outline" size="lg">
                <Download className="mr-2 h-4 w-4" />
                Download PDF Report
              </Button>
            </div>
          </div>
        </Card>
      )}
    </div>
  );
};
